---

- name: Read os specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}-{{ ansible_distribution_release | lower }}.yml"

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ opera_dnsui_packages }}"
    update_cache: true
    cache_valid_time: 3600

- name: Copy apache ssl key
  ansible.builtin.copy:
    src: "{{ opera_dnsui_servername }}.key"
    dest: /etc/ssl/private/
    owner: root
    group: ssl-cert
    mode: "0640"
  when: opera_dnsui_servername is defined
  notify:
    - apache restart

- name: Copy apache ssl crt
  ansible.builtin.copy:
    src: "{{ opera_dnsui_servername }}.pem"
    dest: /etc/ssl/certs/
    mode: "0644"
  when: opera_dnsui_servername is defined
  notify:
    - apache restart

- name: Enable apache modules
  community.general.apache2_module:
    name: "{{ item }}"
  with_items: "{{ opera_dnsui_apache_modules }}"

- name: Enable apache conf
  ansible.builtin.command: "a2enconf {{ item }}"
  args:
    creates: "/etc/apache2/conf-enabled/{{ item }}.conf"
  with_items: "{{ opera_dnsui_apache_confs + [apache_php_fmp_conf] }}"
  notify:
    - apache restart

- name: Clone Opera DNS-UI
  ansible.builtin.git:
    repo: "{{ opera_dnsui_repo_url }}"
    dest: "{{ opera_dnsui_dir }}"
    version: "{{ opera_dnsui_repo_version }}"
    update: false
  when: not (opera_dnsui_repo_download_tgz | default(false) | bool)

- name: Download Opera DNS-UI
  block:
    - name: Fetch {{ opera_dnsui_repo_version }}.tar.gz
      delegate_to: localhost
      ansible.builtin.get_url:
        url: "{{ opera_dnsui_repo_download_url }}"
        dest: "{{ _local_tmp }}/opera-dns-ui.tar.gz"
        force: false
        mode: "0600"
    - name: Upload {{ opera_dnsui_repo_download_url | ansible.builtin.basename }}
      ansible.builtin.copy:
        src: "{{ _local_tmp }}/opera-dns-ui.tar.gz"
        dest: /var/tmp/opera-dns-ui.tar.gz
        force: false
        mode: "0600"
    - name: Create {{ opera_dnsui_dir }}
      ansible.builtin.file:
        path: "{{ opera_dnsui_dir }}"
        state: directory
        mode: "0755"
        owner: root
    - name: Unpack {{ opera_dnsui_repo_download_url | ansible.builtin.basename }}
      ansible.builtin.unarchive:
        dest: "{{ opera_dnsui_dir }}"
        src: /var/tmp/opera-dns-ui.tar.gz
        remote_src: true
        extra_opts:
          - --strip-components=1
        creates: "{{ opera_dnsui_dir }}/config"
  when: opera_dnsui_repo_download_tgz | default(false) | bool

- name: Copy apache site config
  ansible.builtin.template:
    src: apache-site.j2
    dest: /etc/apache2/sites-available/opera-dnsui.conf
    mode: "0644"
  notify:
    - apache restart

- name: Enable apache site config
  ansible.builtin.command: a2ensite opera-dnsui
  args:
    creates: /etc/apache2/sites-enabled/opera-dnsui.conf
  notify:
    - apache restart

- name: Copy apache site config
  ansible.builtin.template:
    src: config.ini.j2
    dest: /srv/opera-dnsui/config/config.ini
    mode: "0640"
    owner: root
    group: www-data

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
