---
- name: Converge
  hosts: all
  tasks:
    - name: Apt update
      apt:
        update_cache: true
      changed_when: false
    - name: "Include opera-dns-ui"
      include_role:
        name: "ansible-role-opera-dns-ui"
