# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: molecule test
on:
  pull_request:
  push:
  schedule:
    - cron: "20 6 * * 1"
jobs:
  ansible-latest:
    name: latest ansible version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install test dependencies.
        run: pip3 install requests ansible molecule "molecule-plugins[docker]" yamllint ansible-lint "requests<2.29" "urllib3<2"

      - name: run molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  ansible-pinned:
    name: pinned ansible version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install test dependencies.
        run: pip3 install requests "ansible==7.4.0" "molecule[docker,lint]==3.5.2" "yamllint==1.26.0" "ansible-lint==6.4.0" "requests<2.29" "urllib3<2"

      - name: run molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
