# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: molecule test
on:
  pull_request:
  push:
  schedule:
    - cron: "20 6 * * 1"
jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          #- latest ansible
          - pinned ansible
        distro:
          - debian13
          - debian12
        include:
          #- ansible: latest ansible
          #  pip3deps: 'ansible "molecule==25.6.0" "molecule-plugins[docker]" yamllint ansible-lint "requests<2.29" "urllib3<2"'
          - ansible: pinned ansible
            pip3deps: '"ansible==11.13.0" "ansible-core==2.18.15" "molecule==25.6.0" "molecule-plugins==23.7.0" "molecule-plugins[docker]" "yamllint==1.38.0" "ansible-lint==26.4.0" "requests==2.32.4" "urllib3==2.6.3"'
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'ansible-role-opera-dns-ui'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13.5  # w/ 3.11 the role is not found

      - name: Install test dependencies.
        run: pip3 install ${{ matrix.pip3deps }}

      - name: Install collections required on ansible 2.9
        run: ansible-galaxy collection install community.general
        if: ${{ matrix.ansible == 'legacy ansible' }}

      - name: debug ansible version
        run: ansible --version

      - name: debug pwd
        run: pwd
      - name: debug ls
        run: ls

      - name: run molecule tests
        run: molecule test
        working-directory: 'ansible-role-opera-dns-ui'
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          ANSIBLE_ROLES_PATH: '.'
